#!/bin/bash

rm -f Makefile
touch Makefile
echo    "C=ghc"                   >> Makefile
echo    "FLAGS=-O2 -threaded"     >> Makefile
echo    ""                        >> Makefile
echo    ".PHONY: softclean clean" >> Makefile
echo    ""                        >> Makefile
echo    "$1:"                     >> Makefile
echo -e "\t\$(C) \$(FLAGS) $1.hs" >> Makefile
echo    ""                        >> Makefile
echo    "clean:"                  >> Makefile
echo -e "\trm -f *.o *.hi $1"     >> Makefile
echo    ""                        >> Makefile
echo    "softclean:"              >> Makefile
echo -e "\trm -f *.o *.hi"        >> Makefile
